### ISSUE TITLE
Duplicate effort?

### ISSUE THREAD

**Issue by qwertychouskie** [kbiElude/VKGL#8]
I hate to be "that guy", but wouldn't it make more sense to collab with https://github.com/Think-Silicon/GLOVE rather than duplicate effort?

**Comment by kbiElude** [comment]
That's a very fair question and there's a number of angles I could take when answering it.

The quickest response would be: GLOVE is about OpenGL ES, not OpenGL. There's a world of difference between the two APIs, especially if at some point a vile idea of adding support for Compatibility Profile starts lighting up in your plans for the project's future goals.

Another observation would be that they currently implement core ES 2.0. Feature set of GL 3.2 which is what I'm aiming at for v1.0 is massively, massively larger than ES 2.0.

This leads us to another point, which is: an ES/GL implementation is usually much more difficult to follow and debug than one which implements only one of the two. This is not a commercial project, so I'd prefer not to take that path, since it a) would hinder project development's pace, b) might make the project less fun to work on in a long run

Finally, technical stuff. I don't know GLOVE's codebase but given they aim at mobile support, I'd assume they're not exactly interested into streamlining their backend into multiple threads or queue family types, which is what I'm intending to do in VKGL. VKGL is fun because one of the hopes I have for it is to make it work faster than native GL implementations of desktop vendors. It may or may not ultimately work out, but VKGL is being written in a way where I can experiment with various approaches to the backend without having to rewrite massive amounts of time. This, I might also add, is one of the reasons the whole infrastructure's bring-up is taking so much time.

**Comment by qwertychouskie** [comment]
Yes, this can be closed.  I look forward to seeing where this project goes.

**Comment by qwertychouskie** [comment]
Hmm, now there's Zink (https://www.collabora.com/news-and-blog/blog/2018/10/31/introducing-zink-opengl-implementation-vulkan/) that already supports GL 2.1/GLES2.0, supports 3.0 on some hardware (https://www.collabora.com/news-and-blog/blog/2018/10/31/introducing-zink-opengl-implementation-vulkan/#qcom436), and will probably support GL 3.2+ soon.  Any thoughts on this?

**Comment by kbiElude** [comment]
No thoughts :-) I appreciate seeing other people working on similar initiatives, the more of us the merrier, but their goals are slightly different from mine. In specific, Zink only appears to support OpenGL 2.1 (OK, plus a handful of extensions, as the web site claims) which means compatibility profile functionality <thunder sound>.

Compatibility profile implies things like glBegin() / glEnd() and I have no intent of spending time right now on working out the best way with which these could work under Vulkan. The crux here is that it really is not that difficult to make these things work using a naive single-threaded approach, it's just a huge bulk of furious keyboard typing that has to be done. The real fun starts when you start aiming for the best performance Vulkan has to offer. And GL 2.1 is.. not exactly compatible with how actual hardware works these days :-)

As I said earlier, there might come time when I start looking at compatibility profile with more interest. Right now, there are way more interesting challenges on the table and they're keeping me busy enough not to have a need to glance at that area.

**Comment by qwertychouskie** [comment]
The main point I was trying to make is that at the current rate of progression (it now already has GL 3.0 on some hardware) it will most likely support GL3.2+ very soon.  Either way, cool to see multiple people working on GL-over-Vulkan.

**Comment by Michael-Lfx** [comment]
> The main point I was trying to make is that at the current rate of progression (it now already has GL 3.0 on some hardware) it will most likely support GL3.2+ very soon. Either way, cool to see multiple people working on GL-over-Vulkan.

A quick question. Is Zink also implementing EGL? GLOVE has both EGL and GLES 2.0. But they are not multithread supported yet. On they agenda  release 0.4 will have multithread support. @qwertychouskie

**Comment by Michael-Lfx** [comment]
> AFAIK Zink implements the Gallium API, meaning anything supported by the Gallium GL/GLES should in theory be supported by Zink, though not completely sure. Maybe ask kusma on #dri-devel on Freenode.

Thank you. I haven't tried Freenode yet. And I have little knowledge about Gallium. Sorry. But I am still wondering how they implement EGL.
